# Generated by Django 5.2.1 on 2025-05-27 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Supervisores',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='libretas.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaLibreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('semana', models.IntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('NO_ENTREGADO', 'No Entregado')], default='PENDIENTE', max_length=20)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libretas.conductor')),
            ],
            options={
                'verbose_name': 'Entrega de Libreta',
                'verbose_name_plural': 'Entregas de Libretas',
                'unique_together': {('conductor', 'mes', 'anio', 'semana')},
            },
        ),
    ]
