# Generated by Django 4.2.18 on 2025-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libretas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregalibreta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('NO_ENTREGADO', 'No Entregado'), ('DESVINCULADO', 'Desvinculado')], default='PENDIENTE', max_length=20),
        ),
    ]
